POST http://localhost:3000/api/users
Content-Type: application/json

{
  "username":"ajay",
  "name":"Ajay",
  "password":"weak password"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "username":"ajay",
  "password":"weak password"
}

###

